services:
  wanderer_notifier:
    image: guarzo/wanderer-notifier:v1
    restart: unless-stopped
    environment:
      PORT: "4000"
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_CHANNEL_ID: ${DISCORD_CHANNEL_ID}
      MAP_URL_WITH_NAME: ${MAP_URL_WITH_NAME}
      MAP_TOKEN: ${MAP_TOKEN}
      LICENSE_KEY: ${LICENSE_KEY}
    ports:
      - "${PORT:-4000}:4000"
    deploy:
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PORT:-4000}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  wanderer_data: