services:
  wanderer_notifier:
    image: guarzo/wanderer-notifier:latest
    container_name: wanderer
    restart: unless-stopped
    environment:
      # Core application configuration
      WANDERER_PORT: "4000"
      WANDERER_DISCORD_BOT_TOKEN: ${WANDERER_DISCORD_BOT_TOKEN}
      WANDERER_DISCORD_CHANNEL_ID: ${WANDERER_DISCORD_CHANNEL_ID}
      WANDERER_MAP_URL: ${WANDERER_MAP_URL}
      WANDERER_MAP_TOKEN: ${WANDERER_MAP_TOKEN}
      WANDERER_LICENSE_KEY: ${WANDERER_LICENSE_KEY}

      # Feature flags
      WANDERER_FEATURE_KILL_CHARTS: "false"
      WANDERER_FEATURE_MAP_CHARTS: "false"
    ports:
      - "${WANDERER_PORT:-4000}:4000"
    deploy:
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:${WANDERER_PORT:-4000}/health",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - wanderer_data:/app/data

volumes:
  wanderer_data:
    name: wanderer_data
