services:
  wanderer_notifier:
    image: guarzo/wanderer-notifier:v1
    container_name: wanderer-notifier
    restart: unless-stopped
    environment:
      # Core application configuration
      WANDERER_PORT: "4000"
      WANDERER_DISCORD_BOT_TOKEN: ${WANDERER_DISCORD_BOT_TOKEN}
      WANDERER_DISCORD_CHANNEL_ID: ${WANDERER_DISCORD_CHANNEL_ID}
      WANDERER_MAP_URL: ${WANDERER_MAP_URL}
      WANDERER_MAP_TOKEN: ${WANDERER_MAP_TOKEN}
      WANDERER_LICENSE_KEY: ${WANDERER_LICENSE_KEY}

      # Database configuration
      WANDERER_DB_HOST: postgres
      WANDERER_DB_USER: postgres
      WANDERER_DB_PASSWORD: postgres
      WANDERER_DB_NAME: wanderer_notifier
      WANDERER_DB_PORT: "5432"
    ports:
      - "${WANDERER_PORT:-4000}:4000"
    depends_on:
      db_init:
        condition: service_completed_successfully
    volumes:
      - wanderer_data:/app/data
    deploy:
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:4000/health",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Database service
  postgres:
    image: postgres:16-alpine
    container_name: wanderer-postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${WANDERER_DB_USER:-postgres}
      - POSTGRES_PASSWORD=${WANDERER_DB_PASSWORD:-postgres}
      - POSTGRES_DB=${WANDERER_DB_NAME:-wanderer_notifier}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Database initialization container
  db_init:
    image: guarzo/wanderer-notifier:latest
    profiles: ["database"]
    environment:
      # Database configuration
      WANDERER_DB_HOST: postgres
      WANDERER_DB_USER: ${WANDERER_DB_USER:-postgres}
      WANDERER_DB_PASSWORD: ${WANDERER_DB_PASSWORD:-postgres}
      WANDERER_DB_NAME: ${WANDERER_DB_NAME:-wanderer_notifier}
      WANDERER_DB_PORT: "5432"
    command: sh -c '/app/bin/wanderer_notifier eval "WandererNotifier.Release.createdb()" && /app/bin/wanderer_notifier eval "WandererNotifier.Release.migrate()"'
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  wanderer_data:
  postgres_data:
    name: wanderer_postgres_data
  db_backups:
    name: wanderer_db_backups
