services:
  wanderer_notifier_test:
    build:
      context: .
      dockerfile: Dockerfile.secure
      secrets:
        - notifier_token
    container_name: wanderer-notifier-test
    environment:
      - NOTIFIER_API_TOKEN_FILE=/run/secrets/notifier_token
    secrets:
      - notifier_token
    ports:
      - "4001:4000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

secrets:
  notifier_token:
    file: ./secrets/notifier_token.txt