services:
  wanderer_notifier:
    image: guarzo/wanderer-notifier:latest
    container_name: wanderer_notifier
    restart: unless-stopped
    environment:
      # Environment setting
      - MIX_ENV=prod

      # Discord Configuration
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      
      # Map Configuration
      - MAP_URL_WITH_NAME=${MAP_URL_WITH_NAME}
      - MAP_TOKEN=${MAP_TOKEN}
      
      # License Configuration
      - LICENSE_KEY=${LICENSE_KEY}
      # BOT_API_TOKEN is not needed for production (uses a constant value)
      - LICENSE_MANAGER_API_URL=${LICENSE_MANAGER_API_URL}
      
      # Application Configuration
      # The PORT environment variable controls the web server port
      # This is used by both the container and the application
      - PORT=${PORT:-4000}
      - HOST=${HOST:-0.0.0.0}
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    volumes:
      - wanderer_data:/app/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: unless-stopped
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "${PORT:-4000}"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  wanderer_data: 