name: "Common Versioning"
description: "Generate version and Docker tag information based on mode (adhoc, automatic, release)"
inputs:
  mode:
    description: "Mode: adhoc, automatic, or release"
    required: true
  branch:
    description: "Branch name (required for adhoc mode)"
    required: false
  version_type:
    description: "Version increment type (required for release mode)"
    required: false
runs:
  using: "composite"
  steps:
    - name: Run versioning script
      shell: bash
      run: |
        SHORT_SHA=$(git rev-parse --short HEAD)
        echo "short_sha=${SHORT_SHA}" >> "$GITHUB_OUTPUT"
        if [ "${{ inputs.mode }}" = "adhoc" ]; then
          if [ -z "${{ inputs.branch }}" ]; then
            echo "Branch input is required for adhoc mode"
            exit 1
          fi
          SAFE_BRANCH=$(echo "${{ inputs.branch }}" | sed 's/\//-/g')
          CURRENT_VERSION=$(./scripts/version.sh get)
          FULL_VERSION="${CURRENT_VERSION}-${SAFE_BRANCH}+$(date +'%Y%m%d').${SHORT_SHA}"
          DOCKER_TAG_LIST="guarzo/wanderer-notifier:branch-${SAFE_BRANCH},guarzo/wanderer-notifier:branch-${SAFE_BRANCH}-$(date +'%Y%m%d')-${SHORT_SHA}"
          echo "version=${CURRENT_VERSION}" >> "$GITHUB_OUTPUT"
          echo "full_version=${FULL_VERSION}" >> "$GITHUB_OUTPUT"
          echo "safe_branch=${SAFE_BRANCH}" >> "$GITHUB_OUTPUT"
          echo "docker_tags=${DOCKER_TAG_LIST}" >> "$GITHUB_OUTPUT"
        elif [ "${{ inputs.mode }}" = "automatic" ]; then
          DEV_VERSION="dev-$(date +'%Y%m%d')-${SHORT_SHA}"
          DOCKER_TAGS="guarzo/wanderer-notifier:dev,guarzo/wanderer-notifier:sha-${SHORT_SHA}"
          echo "dev_version=${DEV_VERSION}" >> "$GITHUB_OUTPUT"
          echo "docker_tags=${DOCKER_TAGS}" >> "$GITHUB_OUTPUT"
        elif [ "${{ inputs.mode }}" = "release" ]; then
          chmod +x ./scripts/version.sh
          NEW_VERSION=$(./scripts/version.sh bump ${{ inputs.version_type }})
          FULL_VERSION=$(./scripts/version.sh full)
          ./scripts/version.sh update ${{ inputs.version_type }}
          DOCKER_TAGS=$(./scripts/version.sh tags)
          DOCKER_TAG_LIST=""
          while IFS= read -r tag; do
            if [ -n "$DOCKER_TAG_LIST" ]; then
              DOCKER_TAG_LIST="${DOCKER_TAG_LIST},guarzo/wanderer-notifier:${tag}"
            else
              DOCKER_TAG_LIST="guarzo/wanderer-notifier:${tag}"
            fi
          done <<< "$DOCKER_TAGS"
          echo "version=${NEW_VERSION}" >> "$GITHUB_OUTPUT"
          echo "full_version=${FULL_VERSION}" >> "$GITHUB_OUTPUT"
          echo "docker_tags=${DOCKER_TAG_LIST}" >> "$GITHUB_OUTPUT"
        else
          echo "Invalid mode: ${{ inputs.mode }}"
          exit 1
        fi
