#!/bin/sh

# Environment variables for Wanderer Notifier
# This script supports both the legacy and new naming conventions

# Core Discord configuration
export DISCORD_BOT_TOKEN="${WANDERER_DISCORD_BOT_TOKEN:-${DISCORD_BOT_TOKEN:-}}"
export WANDERER_DISCORD_BOT_TOKEN="${WANDERER_DISCORD_BOT_TOKEN:-${DISCORD_BOT_TOKEN:-}}"
export DISCORD_CHANNEL_ID="${WANDERER_DISCORD_CHANNEL_ID:-${DISCORD_CHANNEL_ID:-}}"
export WANDERER_DISCORD_CHANNEL_ID="${WANDERER_DISCORD_CHANNEL_ID:-${DISCORD_CHANNEL_ID:-}}"

# License configuration
export LICENSE_KEY="${WANDERER_LICENSE_KEY:-${LICENSE_KEY:-}}"
export WANDERER_LICENSE_KEY="${WANDERER_LICENSE_KEY:-${LICENSE_KEY:-}}"

# License manager URL configuration
export LICENSE_MANAGER_URL="${WANDERER_LICENSE_MANAGER_URL:-${LICENSE_MANAGER_URL:-https://lm.wanderer.ltd}}"
export WANDERER_LICENSE_MANAGER_URL="${WANDERER_LICENSE_MANAGER_URL:-${LICENSE_MANAGER_URL:-https://lm.wanderer.ltd}}"

# Map configuration
export MAP_URL="${MAP_URL:-${WANDERER_MAP_URL:-}}"
export WANDERER_MAP_URL="${WANDERER_MAP_URL:-${MAP_URL:-}}"
export MAP_NAME="${MAP_NAME:-${WANDERER_MAP_NAME:-}}"
export WANDERER_MAP_NAME="${WANDERER_MAP_NAME:-${MAP_NAME:-}}"
export MAP_API_KEY="${MAP_API_KEY:-${MAP_TOKEN:-${WANDERER_MAP_TOKEN:-}}}"
export MAP_TOKEN="${MAP_TOKEN:-${MAP_API_KEY:-${WANDERER_MAP_TOKEN:-}}}"
export WANDERER_MAP_TOKEN="${WANDERER_MAP_TOKEN:-${MAP_API_KEY:-${MAP_TOKEN:-}}}"
export MAP_URL_WITH_NAME="${WANDERER_MAP_URL_WITH_NAME:-${MAP_URL_WITH_NAME:-}}"
export WANDERER_MAP_URL_WITH_NAME="${WANDERER_MAP_URL_WITH_NAME:-${MAP_URL_WITH_NAME:-}}"

# Web server configuration
export PORT="${WANDERER_PORT:-${PORT:-4000}}"
export WANDERER_PORT="${WANDERER_PORT:-${PORT:-4000}}"
export HOST="${WANDERER_HOST:-${HOST:-0.0.0.0}}"
export WANDERER_HOST="${WANDERER_HOST:-${HOST:-0.0.0.0}}"
export SCHEME="${WANDERER_SCHEME:-${SCHEME:-http}}"
export WANDERER_SCHEME="${WANDERER_SCHEME:-${SCHEME:-http}}"

# Database configuration
export POSTGRES_USER="${WANDERER_DB_USER:-${POSTGRES_USER:-postgres}}"
export WANDERER_DB_USER="${WANDERER_DB_USER:-${POSTGRES_USER:-postgres}}"
export POSTGRES_PASSWORD="${WANDERER_DB_PASSWORD:-${POSTGRES_PASSWORD:-postgres}}"
export WANDERER_DB_PASSWORD="${WANDERER_DB_PASSWORD:-${POSTGRES_PASSWORD:-postgres}}"
export POSTGRES_HOST="${WANDERER_DB_HOST:-${POSTGRES_HOST:-postgres}}"
export WANDERER_DB_HOST="${WANDERER_DB_HOST:-${POSTGRES_HOST:-postgres}}"
export POSTGRES_DB="${WANDERER_DB_NAME:-${POSTGRES_DB:-wanderer_notifier}}"
export WANDERER_DB_NAME="${WANDERER_DB_NAME:-${POSTGRES_DB:-wanderer_notifier}}"
export POSTGRES_PORT="${WANDERER_DB_PORT:-${POSTGRES_PORT:-5432}}"
export WANDERER_DB_PORT="${WANDERER_DB_PORT:-${POSTGRES_PORT:-5432}}"

# Feature flags
export ENABLE_KILL_CHARTS="${WANDERER_FEATURE_KILL_CHARTS:-${ENABLE_KILL_CHARTS:-false}}"
export WANDERER_FEATURE_KILL_CHARTS="${WANDERER_FEATURE_KILL_CHARTS:-${ENABLE_KILL_CHARTS:-false}}"
export ENABLE_MAP_CHARTS="${WANDERER_FEATURE_MAP_CHARTS:-${ENABLE_MAP_CHARTS:-false}}"
export WANDERER_FEATURE_MAP_CHARTS="${WANDERER_FEATURE_MAP_CHARTS:-${ENABLE_MAP_CHARTS:-false}}"
export ENABLE_TRACK_KSPACE_SYSTEMS="${WANDERER_FEATURE_TRACK_KSPACE:-${ENABLE_TRACK_KSPACE_SYSTEMS:-true}}"
export WANDERER_FEATURE_TRACK_KSPACE="${WANDERER_FEATURE_TRACK_KSPACE:-${ENABLE_TRACK_KSPACE_SYSTEMS:-true}}"
export ENABLE_SYSTEM_TRACKING="${WANDERER_FEATURE_SYSTEM_TRACKING:-${ENABLE_SYSTEM_TRACKING:-true}}"
export WANDERER_FEATURE_SYSTEM_TRACKING="${WANDERER_FEATURE_SYSTEM_TRACKING:-${ENABLE_SYSTEM_TRACKING:-true}}"
export ENABLE_CHARACTER_TRACKING="${WANDERER_FEATURE_CHARACTER_TRACKING:-${ENABLE_CHARACTER_TRACKING:-true}}"
export WANDERER_FEATURE_CHARACTER_TRACKING="${WANDERER_FEATURE_CHARACTER_TRACKING:-${ENABLE_CHARACTER_TRACKING:-true}}"

# Cache configuration
export CACHE_DIR="${WANDERER_CACHE_DIR:-${CACHE_DIR:-/app/data/cache}}"
export WANDERER_CACHE_DIR="${WANDERER_CACHE_DIR:-${CACHE_DIR:-/app/data/cache}}"

# Application configuration
export MIX_ENV=prod
export LANG="${LANG:-en_US.UTF-8}"
export TZ="${TZ:-UTC}"
export CONFIG_PATH="/app/etc"

# API token handling
if [ "${MIX_ENV}" = "prod" ]; then
  # In production mode
  if [ -n "${NOTIFIER_API_TOKEN}" ] || [ -n "${WANDERER_NOTIFIER_API_TOKEN}" ] || [ -n "${API_TOKEN}" ]; then
    # If environment variables are set, use them (security override)
    export NOTIFIER_API_TOKEN="${NOTIFIER_API_TOKEN:-${WANDERER_NOTIFIER_API_TOKEN:-${API_TOKEN}}}"
    export API_TOKEN="${API_TOKEN:-${NOTIFIER_API_TOKEN:-${WANDERER_NOTIFIER_API_TOKEN}}}"
    export WANDERER_NOTIFIER_API_TOKEN="${WANDERER_NOTIFIER_API_TOKEN:-${NOTIFIER_API_TOKEN:-${API_TOKEN}}}"
    echo "Using API token from environment variable"
  else
    # Otherwise, clear token environment variables to use baked-in value
    echo "Using baked-in API token from release configuration"
    unset NOTIFIER_API_TOKEN
    unset API_TOKEN
    unset WANDERER_NOTIFIER_API_TOKEN
  fi
else
  # In development mode, ensure all variables are set for compatibility
  export NOTIFIER_API_TOKEN="${NOTIFIER_API_TOKEN:-${WANDERER_NOTIFIER_API_TOKEN:-${API_TOKEN:-}}}"
  export API_TOKEN="${API_TOKEN:-${NOTIFIER_API_TOKEN:-${WANDERER_NOTIFIER_API_TOKEN:-}}}"
  export WANDERER_NOTIFIER_API_TOKEN="${WANDERER_NOTIFIER_API_TOKEN:-${NOTIFIER_API_TOKEN:-${API_TOKEN:-}}}"
fi

# Notification configuration
export NOTIFICATIONS_ENABLED="${NOTIFICATIONS_ENABLED:-${WANDERER_NOTIFICATIONS_ENABLED:-true}}"
export WANDERER_NOTIFICATIONS_ENABLED="${WANDERER_NOTIFICATIONS_ENABLED:-${NOTIFICATIONS_ENABLED:-true}}"
export KILL_NOTIFICATIONS_ENABLED="${KILL_NOTIFICATIONS_ENABLED:-${WANDERER_KILL_NOTIFICATIONS_ENABLED:-true}}"
export WANDERER_KILL_NOTIFICATIONS_ENABLED="${WANDERER_KILL_NOTIFICATIONS_ENABLED:-${KILL_NOTIFICATIONS_ENABLED:-true}}"
export SYSTEM_NOTIFICATIONS_ENABLED="${SYSTEM_NOTIFICATIONS_ENABLED:-${WANDERER_SYSTEM_NOTIFICATIONS_ENABLED:-true}}"
export WANDERER_SYSTEM_NOTIFICATIONS_ENABLED="${WANDERER_SYSTEM_NOTIFICATIONS_ENABLED:-${SYSTEM_NOTIFICATIONS_ENABLED:-true}}"
export CHARACTER_NOTIFICATIONS_ENABLED="${CHARACTER_NOTIFICATIONS_ENABLED:-${WANDERER_CHARACTER_NOTIFICATIONS_ENABLED:-true}}"
export WANDERER_CHARACTER_NOTIFICATIONS_ENABLED="${WANDERER_CHARACTER_NOTIFICATIONS_ENABLED:-${CHARACTER_NOTIFICATIONS_ENABLED:-true}}"
export ENABLE_STATUS_MESSAGES="${ENABLE_STATUS_MESSAGES:-${WANDERER_ENABLE_STATUS_MESSAGES:-true}}"
export WANDERER_ENABLE_STATUS_MESSAGES="${WANDERER_ENABLE_STATUS_MESSAGES:-${ENABLE_STATUS_MESSAGES:-true}}"
export TRACK_KSPACE_ENABLED="${TRACK_KSPACE_ENABLED:-${WANDERER_FEATURE_TRACK_KSPACE:-true}}"
export WANDERER_FEATURE_TRACK_KSPACE="${WANDERER_FEATURE_TRACK_KSPACE:-${TRACK_KSPACE_ENABLED:-true}}"

# Character configuration
export CHARACTER_EXCLUDE_LIST="${CHARACTER_EXCLUDE_LIST:-${WANDERER_CHARACTER_EXCLUDE_LIST:-}}"
export WANDERER_CHARACTER_EXCLUDE_LIST="${WANDERER_CHARACTER_EXCLUDE_LIST:-${CHARACTER_EXCLUDE_LIST:-}}"

# Tracking configuration
export SYSTEM_TRACKING_ENABLED="${SYSTEM_TRACKING_ENABLED:-${WANDERER_FEATURE_SYSTEM_TRACKING:-true}}"
export WANDERER_FEATURE_SYSTEM_TRACKING="${WANDERER_FEATURE_SYSTEM_TRACKING:-${SYSTEM_TRACKING_ENABLED:-true}}"
export CHARACTER_TRACKING_ENABLED="${CHARACTER_TRACKING_ENABLED:-${WANDERER_FEATURE_CHARACTER_TRACKING:-true}}"
export WANDERER_FEATURE_CHARACTER_TRACKING="${WANDERER_FEATURE_CHARACTER_TRACKING:-${CHARACTER_TRACKING_ENABLED:-true}}"
export DISABLE_STATUS_MESSAGES="${DISABLE_STATUS_MESSAGES:-${WANDERER_DISABLE_STATUS_MESSAGES:-false}}"
export WANDERER_DISABLE_STATUS_MESSAGES="${WANDERER_DISABLE_STATUS_MESSAGES:-${DISABLE_STATUS_MESSAGES:-false}}" 