name: "Common Checkout and Cache"
description: "Checkout code and restore dependencies cache"
inputs:
  branch:
    description: "Branch to checkout"
    required: false
    default: "main"
  fetch-depth:
    description: "Git fetch depth"
    required: false
    default: "0"
  cache-key-prefix:
    description: "Cache key prefix (e.g., mix)"
    required: true
  cache-paths:
    description: "Cache paths to restore (newline separated)"
    required: false
    default: |
      deps
      _build
      priv/static
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}
        fetch-depth: ${{ inputs.fetch-depth }}
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.cache-paths }}
        key: ${{ runner.os }}-${{ inputs.cache-key-prefix }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.cache-key-prefix }}-
          ${{ runner.os }}-mix-
