version: "3.8"
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        USERNAME: elixir
        NODE_VERSION: 20.x
        INSTALL_ELIXIR_LS: "true"
    volumes:
      - ..:/workspace:cached
      - claude-code-bashhistory:/commandhistory
      - claude-code-config:/home/elixir/.claude
      - elixir-ls-cache:/home/elixir/.elixir-ls
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
      - CLAUDE_CONFIG_DIR=/home/elixir/.claude
      - POWERLEVEL9K_DISABLE_GITSTATUS=true
    command: sleep infinity
    user: elixir
    ports:
      - "${HOST_BACKEND_PORT:-4000}:4000" # Backend API
      - "${HOST_DASHBOARD_PORT:-4001}:4001" # Phoenix LiveDashboard
      - "${HOST_FRONTEND_PORT:-5173}:5173" # Vite dev server
    # This allows the container to access host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  claude-code-bashhistory:
  claude-code-config:
  elixir-ls-cache:
