defmodule WandererNotifier.Repo.Migrations.AddKillStats do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tracked_characters, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:character_id, :bigint, null: false)
      add(:character_name, :text, null: false)
      add(:corporation_id, :bigint)
      add(:corporation_name, :text)
      add(:alliance_id, :bigint)
      add(:alliance_name, :text)
      add(:tracked_since, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')"))

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:tracked_characters, [:character_id],
        name: "tracked_characters_unique_character_id_index"
      )
    )

    create table(:killmails, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:killmail_id, :bigint, null: false)
      add(:kill_time, :utc_datetime_usec)
      add(:solar_system_id, :bigint)
      add(:solar_system_name, :text)
      add(:region_id, :bigint)
      add(:region_name, :text)
      add(:total_value, :decimal)
      add(:character_role, :text)

      add(
        :related_character_id,
        references(:tracked_characters,
          column: :character_id,
          name: "killmails_related_character_id_fkey",
          type: :bigint
        ),
        null: false
      )

      add(:related_character_name, :text)
      add(:ship_type_id, :bigint)
      add(:ship_type_name, :text)
      add(:zkb_data, :map)
      add(:victim_data, :map)
      add(:attacker_data, :map)
      add(:processed_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')"))

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:killmails, [:killmail_id, :character_role, :related_character_id],
        name: "killmails_unique_killmail_index"
      )
    )

    create table(:killmail_statistics, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:period_type, :text)
      add(:period_start, :date)
      add(:period_end, :date)
      add(:character_id, :bigint, null: false)
      add(:character_name, :text)
      add(:kills_count, :bigint, default: 0)
      add(:deaths_count, :bigint, default: 0)
      add(:isk_destroyed, :decimal, default: "0")
      add(:isk_lost, :decimal, default: "0")
      add(:solo_kills_count, :bigint, default: 0)
      add(:final_blows_count, :bigint, default: 0)
      add(:region_activity, :map, default: %{})
      add(:ship_usage, :map, default: %{})
      add(:top_victim_corps, :map, default: %{})
      add(:top_victim_ships, :map, default: %{})
      add(:detailed_ship_usage, :map, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:killmail_statistics, [:character_id, :period_type, :period_start],
        name: "killmail_statistics_unique_character_period_index"
      )
    )
  end

  def down do
    drop_if_exists(
      unique_index(:killmail_statistics, [:character_id, :period_type, :period_start],
        name: "killmail_statistics_unique_character_period_index"
      )
    )

    drop(table(:killmail_statistics))

    drop_if_exists(
      unique_index(:killmails, [:killmail_id, :character_role, :related_character_id],
        name: "killmails_unique_killmail_index"
      )
    )

    drop(constraint(:killmails, "killmails_related_character_id_fkey"))

    drop(table(:killmails))

    drop_if_exists(
      unique_index(:tracked_characters, [:character_id],
        name: "tracked_characters_unique_character_id_index"
      )
    )

    drop(table(:tracked_characters))
  end
end
