name: Ad-hoc

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build"
        required: true
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0 # required for getting commit SHA

      - name: Generate version string
        id: version
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          DATE=$(date +'%Y%m%d')
          # Replace slashes in branch name with hyphens for Docker tag
          SAFE_BRANCH=$(echo "${{ github.event.inputs.branch }}" | sed 's/\//-/g')

          echo "short_sha=${SHORT_SHA}" >> "$GITHUB_OUTPUT"
          echo "safe_branch=${SAFE_BRANCH}" >> "$GITHUB_OUTPUT"
          echo "version=branch-${SAFE_BRANCH}" >> "$GITHUB_OUTPUT"
          echo "docker_version=branch-${SAFE_BRANCH}-${DATE}-${SHORT_SHA}" >> "$GITHUB_OUTPUT"

          echo "Generated SHA: ${SHORT_SHA}"
          echo "Sanitized branch name: ${SAFE_BRANCH}"
          echo "Docker version: branch-${SAFE_BRANCH}-${DATE}-${SHORT_SHA}"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "renderer/package-lock.json"

      - name: Build React application
        run: |
          # Ensure the static app directory exists first
          mkdir -p priv/static/app
          cd renderer
          npm ci
          npm run build
          cd ..
          # Copy the built React app to the static directory
          cp -r renderer/dist/* priv/static/app/ || true

      - name: Update version in mix.exs
        run: |
          # Update the version with a valid Elixir version format
          sed -i "s/version: \"[^\"]*\"/version: \"${{ steps.version.outputs.version }}\"/" mix.exs
          cat mix.exs

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: guarzo
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build and Push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            guarzo/wanderer-notifier:branch-${{ steps.version.outputs.safe_branch }}
            guarzo/wanderer-notifier:${{ steps.version.outputs.docker_version }}
          build-args: |
            WANDERER_NOTIFIER_API_TOKEN=${{ secrets.NOTIFIER_API_TOKEN }}
            NOTIFIER_API_TOKEN=${{ secrets.NOTIFIER_API_TOKEN }}
            WANDERER_APP_VERSION=${{ steps.version.outputs.docker_version }}
            APP_VERSION=${{ steps.version.outputs.docker_version }}
          load: true

      # Test the Docker image to verify it can start
      - name: Test Docker image
        run: |
          echo "Testing Docker image startup..."
          # Only verify GLIBC version and basic Elixir functionality without starting the full app
          docker run --rm guarzo/wanderer-notifier:branch-${{ steps.version.outputs.safe_branch }} /bin/sh -c "echo 'GLIBC Version:' && ldd --version | head -n1 && /app/bin/wanderer_notifier eval '1+1'"
        continue-on-error: true
