name: Build and Push Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required for pushing tags

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Compute image tag from date and SHA
        id: tag
        run: |
          # Compute tag based on current date and short SHA
          DATE_TAG=$(date +'%Y%m%d')
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "image_tag=${DATE_TAG}" >> "$GITHUB_OUTPUT"
          echo "image_tag_with_sha=${DATE_TAG}_${SHORT_SHA}" >> "$GITHUB_OUTPUT"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: guarzo
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            APP_VERSION=${{ steps.version.outputs.version }}-test
            NOTIFIER_API_TOKEN=${{ secrets.NOTIFIER_API_TOKEN }}
          tags: ${{ steps.meta.outputs.tags }}

      - name: Create and push Git tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag ${{ steps.tag.outputs.image_tag_with_sha }}
          git push origin ${{ steps.tag.outputs.image_tag_with_sha }}
