name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # required for pushing tags

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Compute image tag from date
        id: tag
        run: |
          # Compute tag based on current date, e.g., 20250219
          echo "image_tag=$(date +'%Y%m%d')" >> "$GITHUB_OUTPUT"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ steps.tag.outputs.image_tag }}

      - name: Create and push Git tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag ${{ steps.tag.outputs.image_tag }}
          git push origin ${{ steps.tag.outputs.image_tag }}

