name: Docs

on:
  push:
    branches:
      - main
    paths:
      - 'index.md'
      - 'notifications.md'
      - 'license.md'
      - '_layouts/**'
      - 'assets/**'
      - '_config.yml'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

# Permissions required for GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  deployments: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for proper deployment

      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Create Image Directories
        run: |
          mkdir -p assets/images

      # Copy placeholder images if real ones don't exist
      # In a real scenario, you would have actual images in your repo
      - name: Copy Placeholder Images
        run: |
          if [ ! -f "assets/images/paid-kill.png" ]; then
            echo "Creating placeholder for paid-kill.png"
            convert -size 600x400 canvas:lightblue -font Arial -pointsize 20 -fill black -annotate +30+30 "Licensed Kill Notification Example" assets/images/paid-kill.png
          fi
          
          if [ ! -f "assets/images/free-kill.png" ]; then
            echo "Creating placeholder for free-kill.png"
            convert -size 600x150 canvas:lightgray -font Arial -pointsize 20 -fill black -annotate +30+30 "Free Kill Notification Example" assets/images/free-kill.png
          fi
          
          if [ ! -f "assets/images/paid-character.png" ]; then
            echo "Creating placeholder for paid-character.png"
            convert -size 600x300 canvas:lightgreen -font Arial -pointsize 20 -fill black -annotate +30+30 "Licensed Character Notification Example" assets/images/paid-character.png
          fi
          
          if [ ! -f "assets/images/free-character.png" ]; then
            echo "Creating placeholder for free-character.png"
            convert -size 600x100 canvas:lightgray -font Arial -pointsize 20 -fill black -annotate +30+30 "Free Character Notification Example" assets/images/free-character.png
          fi
          
          if [ ! -f "assets/images/paid-system.png" ]; then
            echo "Creating placeholder for paid-system.png"
            convert -size 600x300 canvas:orange -font Arial -pointsize 20 -fill black -annotate +30+30 "Licensed System Notification Example" assets/images/paid-system.png
          fi
          
          if [ ! -f "assets/images/free-system.png" ]; then
            echo "Creating placeholder for free-system.png"
            convert -size 600x100 canvas:lightgray -font Arial -pointsize 20 -fill black -annotate +30+30 "Free System Notification Example" assets/images/free-system.png
          fi
          
          if [ ! -f "assets/images/dashboard.png" ]; then
            echo "Creating placeholder for dashboard.png"
            convert -size 800x600 canvas:white -font Arial -pointsize 20 -fill black -annotate +30+30 "Wanderer Notifier Dashboard" assets/images/dashboard.png
          fi
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 