name: Docs

on:
  push:
    branches:
      - main
    paths:
      - 'index.md'
      - 'notifications.md'
      - 'license.md'
      - '_layouts/**'
      - 'assets/**'
      - '_config.yml'
      - '.github/workflows/docs.yml'
  release:
    types: [published, created, edited]
  workflow_dispatch:

concurrency:
  group: github-pages-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Setup Ruby & Cache Gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Create Image Directories and Placeholder Images
        run: |
          mkdir -p assets/images
          
          # Create placeholder images if they don't exist
          if [ ! -f "assets/images/paid-kill.png" ]; then
            echo "Creating placeholder for paid-kill.png"
            convert -size 600x400 canvas:lightblue -font Arial -pointsize 20 -fill black -annotate +30+30 "Licensed Kill Notification Example" assets/images/paid-kill.png
          fi
          
          if [ ! -f "assets/images/free-kill.png" ]; then
            echo "Creating placeholder for free-kill.png"
            convert -size 600x150 canvas:lightgray -font Arial -pointsize 20 -fill black -annotate +30+30 "Free Kill Notification Example" assets/images/free-kill.png
          fi
          
          if [ ! -f "assets/images/paid-character.png" ]; then
            echo "Creating placeholder for paid-character.png"
            convert -size 600x300 canvas:lightgreen -font Arial -pointsize 20 -fill black -annotate +30+30 "Licensed Character Notification Example" assets/images/paid-character.png
          fi
          
          if [ ! -f "assets/images/free-character.png" ]; then
            echo "Creating placeholder for free-character.png"
            convert -size 600x100 canvas:lightgray -font Arial -pointsize 20 -fill black -annotate +30+30 "Free Character Notification Example" assets/images/free-character.png
          fi
          
          if [ ! -f "assets/images/paid-system.png" ]; then
            echo "Creating placeholder for paid-system.png"
            convert -size 600x300 canvas:orange -font Arial -pointsize 20 -fill black -annotate +30+30 "Licensed System Notification Example" assets/images/paid-system.png
          fi
          
          if [ ! -f "assets/images/free-system.png" ]; then
            echo "Creating placeholder for free-system.png"
            convert -size 600x100 canvas:lightgray -font Arial -pointsize 20 -fill black -annotate +30+30 "Free System Notification Example" assets/images/free-system.png
          fi
          
          if [ ! -f "assets/images/dashboard.png" ]; then
            echo "Creating placeholder for dashboard.png"
            convert -size 800x600 canvas:white -font Arial -pointsize 20 -fill black -annotate +30+30 "Wanderer Notifier Dashboard" assets/images/dashboard.png
          fi

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
