name: elixir

  - name: Setup elixir
    uses: erlef/setup-beam@v1
    with:
      elixir-version: ${{ matrix.elixir }}
      otp-version: ${{ matrix.otp }}

- name: Clean dependencies
  run: |
    mix deps.clean --all
    rm -rf _build

- name: Get dependencies
  run: |
    mix deps.get
    mix deps.compile --force 