name: Release
run-name: Release - ${{ github.event.inputs.version_type }} version update

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Version increment type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: prod
    steps:
      - name: Initial checkout
        uses: actions/checkout@v3

      - name: Common Checkout and Cache
        uses: ./.github/actions/common-checkout-cache
        with:
          branch: main
          cache-key-prefix: mix
          cache-paths: |
            deps
            _build
            priv/static

      - name: Generate version information
        id: version
        uses: ./.github/actions/common-versioning
        with:
          mode: release
          version_type: ${{ github.event.inputs.version_type }}

      - name: Debug version info
        run: |
          echo "Version: ${{ steps.version.outputs.version }}"
          echo "Full version: ${{ steps.version.outputs.full_version }}"
          echo "Short SHA: ${{ steps.version.outputs.short_sha }}"

      - name: Update workflow title
        run: |
          echo "title=Release - Version v${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY

      - name: Create version bump commit and tag
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

          # Debug git status
          echo "Git status before changes:"
          git status

          # Stage all version-related files
          git add VERSION mix.exs

          echo "Git status after staging:"
          git status

          # Get the version number for commit message
          VERSION="${{ steps.version.outputs.version }}"
          echo "Debug: Version from outputs: $VERSION"

          # Fallback to reading from VERSION file if output is empty
          if [ -z "$VERSION" ]; then
            VERSION=$(cat VERSION)
            echo "Debug: Version from file: $VERSION"
          fi

          if [ -z "$VERSION" ]; then
            echo "Error: Could not determine version number"
            exit 1
          fi

          echo "Using version: $VERSION"

          # Create version bump commit with [skip ci]
          git commit -m "Release version v$VERSION [skip ci]"

          # Create annotated tag
          git tag -a "v$VERSION" -m "Release v$VERSION"

          # Push both the commit and tag
          git push origin main "v$VERSION"

      - name: Common Node.js Setup
        uses: ./.github/actions/common-node-setup
        with:
          node_version: "20"
          cache_dependency_path: "renderer/package-lock.json"

      - name: Install frontend dependencies and build
        run: |
          cd renderer
          npm ci
          npm run build
          cd ..

      - name: Build Docker image (SHA tagged)
        uses: ./.github/actions/common-docker-build
        with:
          context: .
          push: false
          load: true
          tags: guarzo/wanderer-notifier:sha-${{ steps.version.outputs.short_sha }}
          build-args: |
            APP_VERSION=${{ steps.version.outputs.full_version }}
            WANDERER_NOTIFIER_API_TOKEN=${{ secrets.NOTIFIER_API_TOKEN }}
          cache-from: type=registry,ref=guarzo/wanderer-notifier:latest
          cache-to: type=inline

      - name: Test Docker image
        run: |
          echo "Testing Docker image..."
          ./scripts/test_docker_image.sh -t "sha-${{ steps.version.outputs.short_sha }}" --discord-token "${{ secrets.FAKE_DISCORD_TOKEN }}"
          echo "Docker image validation successful!"

      - name: Extract major version
        id: major_version
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          MAJOR_VERSION="v${VERSION%%.*}"
          echo "value=${MAJOR_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Push Docker image with release tags
        uses: ./.github/actions/common-docker-build
        with:
          context: .
          push: true
          tags: guarzo/wanderer-notifier:latest,guarzo/wanderer-notifier:${{ steps.major_version.outputs.value }},guarzo/wanderer-notifier:v${{ steps.version.outputs.version }}
          build-args: |
            APP_VERSION=${{ steps.version.outputs.full_version }}
            WANDERER_NOTIFIER_API_TOKEN=${{ secrets.NOTIFIER_API_TOKEN }}
          cache-from: type=registry,ref=guarzo/wanderer-notifier:latest
          cache-to: type=inline
          docker_username: guarzo
          docker_password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.version.outputs.version }}"
          name: "Release v${{ steps.version.outputs.version }}"
          body: |
            ## Wanderer Notifier v${{ steps.version.outputs.version }}

            Build: ${{ steps.version.outputs.full_version }}

            ### Docker Image
            ```
            docker pull guarzo/wanderer-notifier:v${{ steps.version.outputs.version }}
            ```
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
