name: Official Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version tag'
        required: false
        default: 'v1'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up BEAM
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.14.5'
          otp-version: '25.0'

      - name: Install dependencies and build release
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only prod
          mix deps.compile
          mix release

      - name: Debug Dockerfile
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing files in current directory:"
          ls -la
          echo "Dockerfile content:"
          cat Dockerfile

      - name: Build Docker image
        run: |
          docker build -t guarzo/wanderer-notifier:${{ github.event.inputs.release_version }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: guarzo
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Push Docker image
        run: |
          docker push guarzo/wanderer-notifier:${{ github.event.inputs.release_version }}
