name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      # Add environment variables for testing
      DISCORD_BOT_TOKEN: ${{ secrets.FAKE_DISCORD_TOKEN }}
      WANDERER_DISCORD_BOT_TOKEN: ${{ secrets.FAKE_DISCORD_TOKEN }}
      MIX_ENV: "test"
      CACHE_DIR: "/tmp/wanderer_notifier_cache"
      WANDERER_CACHE_DIR: "/tmp/wanderer_notifier_cache"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.18"
          otp-version: "27"

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-test-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-test-
            ${{ runner.os }}-mix-

      - name: Install dependencies
        run: |
          mix deps.get
          mix deps.compile

      - name: Compile (warnings as errors)
        run: mix compile --warnings-as-errors

      - name: Run tests
        run: mix test

      - name: Generate test coverage
        run: mix test --cover
        continue-on-error: true

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    needs: test
    env:
      MIX_ENV: "dev"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.18"
          otp-version: "27"

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-lint-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-lint-
            ${{ runner.os }}-mix-

      - name: Install dependencies
        run: |
          mix local.hex --force
          mix deps.get
          mix deps.compile

      - name: Check formatting
        run: mix format --check-formatted

      - name: Run code quality checks
        run: mix credo

  docker:
    name: Validate Docker image
    runs-on: ubuntu-latest
    needs: lint
    env:
      MIX_ENV: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required for getting commit history

      - name: Print config provider implementation
        run: |
          echo "Checking Elixir Config.Reader implementation..."
          cat <<EOF > check_config_reader.exs
          IO.puts("Exploring Config.Reader module...")
          Code.ensure_loaded(Config.Reader)

          if function_exported?(Code, :fetch_docs, 1) do
            case Code.fetch_docs(Config.Reader) do
              {:docs_v1, _, _, _, module_doc, _, _} when is_binary(module_doc) ->
                IO.puts("Module docs: \#{String.slice(module_doc, 0, 200)}...")
              _ ->
                IO.puts("No documentation available for Config.Reader")
            end
          end

          if function_exported?(Config.Reader, :read!, 2) do
            IO.puts("Function Config.Reader.read!/2 is exported")
          else
            IO.puts("Function Config.Reader.read!/2 is NOT exported!")
          end

          if function_exported?(Config.Reader, :load, 2) do
            IO.puts("Function Config.Reader.load/2 is exported")
          else
            IO.puts("Function Config.Reader.load/2 is NOT exported!")
          end
          EOF

          elixir check_config_reader.exs

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Generate short SHA
        id: sha
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "short_sha=${SHORT_SHA}" >> "$GITHUB_OUTPUT"
          echo "Using SHA: ${SHORT_SHA}"

      - name: Build Docker image (for testing)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: wanderer-notifier:pr-${{ steps.sha.outputs.short_sha }}
          build-args: |
            APP_VERSION=0.0.0-ci-test

      - name: Full Docker validation with web server
        run: |
          echo "Running comprehensive Docker validation..."
          chmod +x ./scripts/test_docker_image.sh

          # Run full validation including web server startup test
          # No --basic flag to ensure we test the running application
          ./scripts/test_docker_image.sh -i wanderer-notifier -t pr-${{ steps.sha.outputs.short_sha }} --discord-token "${{ secrets.FAKE_DISCORD_TOKEN }}"

          echo "Docker image validation successful!"
