name: Test
run-name: Test - ${{ github.event.head_commit.message || github.event.pull_request.title }}

on:
  push:
    branches: [main]
    paths-ignore:
      - "mix.exs" # Ignore version bump commits
  pull_request:
    branches: [main]

# Cancel in-progress runs for the same branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      DISCORD_BOT_TOKEN: ${{ secrets.FAKE_DISCORD_TOKEN }}
      WANDERER_DISCORD_BOT_TOKEN: ${{ secrets.FAKE_DISCORD_TOKEN }}
      MIX_ENV: "test"
      CACHE_DIR: "/tmp/wanderer_notifier_cache"
      WANDERER_CACHE_DIR: "/tmp/wanderer_notifier_cache"
      WANDERER_NOTIFIER_API_TOKEN: ${{ secrets.NOTIFIER_API_TOKEN }}
      WANDERER_MAP_TOKEN: "empty-token"
      WANDERER_LICENSE_KEY: "empty-license-key"
      WANDERER_MAP_URL: "http://example.com/map?name=testmap"

    outputs:
      cache-key: ${{ steps.cache-key.outputs.value }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Generate a cache key based on mix.lock and elixir version
      - id: cache-key
        run: |
          echo "value=${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}-1.18-27" >> $GITHUB_OUTPUT

      - name: Common Checkout and Cache
        uses: ./.github/actions/common-checkout-cache
        with:
          cache-key-prefix: mix-test
          cache-paths: |
            deps
            _build

      - name: Common Elixir Setup for Test
        uses: ./.github/actions/common-elixir-setup
        with:
          elixir-version: "1.18"
          otp-version: "27"

      - name: Install dependencies
        run: |
          mix deps.get
          mix deps.compile

      - name: Compile (warnings as errors)
        run: mix compile --warnings-as-errors
        continue-on-error: true

      - name: Run tests
        run: mix test 

      - name: Generate test coverage
        run: mix test --cover
        continue-on-error: true

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    needs: test # We depend on test job for the cache
    env:
      MIX_ENV: "dev"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Common Checkout and Cache
        uses: ./.github/actions/common-checkout-cache
        with:
          cache-key-prefix: mix-lint
          cache-paths: |
            deps
            _build

      - name: Common Elixir Setup for Test
        uses: ./.github/actions/common-elixir-setup
        with:
          elixir-version: "1.18"
          otp-version: "27"

      - name: Install dependencies
        run: |
          mix local.hex --force
          mix deps.get
          mix deps.compile

      - name: Check formatting
        run: mix format --check-formatted

      - name: Run code quality checks
        run: mix credo --strict
        continue-on-error: true

  docker:
    name: Validate Docker image
    runs-on: ubuntu-latest
    needs: lint
    env:
      MIX_ENV: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Generate short SHA
        id: sha
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "short_sha=${SHORT_SHA}" >> "$GITHUB_OUTPUT"
          echo "Using SHA: ${SHORT_SHA}"

      - name: Build Docker image (for testing)
        uses: ./.github/actions/common-docker-build
        with:
          context: .
          push: false
          load: true
          tags: wanderer-notifier:pr-${{ steps.sha.outputs.short_sha }}
          build-args: |
            APP_VERSION=0.0.0-ci-test
            WANDERER_NOTIFIER_API_TOKEN=${{ secrets.NOTIFIER_API_TOKEN }}

      - name: Full Docker validation with web server
        env:
          DISCORD_TOKEN: ${{ secrets.FAKE_DISCORD_TOKEN }}
          MAP_URL_WITH_NAME: "http://example.com/map?name=testmap"
          MAP_TOKEN: "test-map-token"
          DISCORD_CHANNEL_ID: "123456789"
          LICENSE_KEY: "test-license-key"
        run: |
          echo "Running comprehensive Docker validation..."
          chmod +x ./scripts/test_docker_image.sh
          ./scripts/test_docker_image.sh -i wanderer-notifier -t pr-${{ steps.sha.outputs.short_sha }} \
            --discord-token "$DISCORD_TOKEN" \
            --env "WANDERER_MAP_URL=$MAP_URL_WITH_NAME" \
            --env "WANDERER_MAP_TOKEN=$MAP_TOKEN" \
            --env "WANDERER_DISCORD_CHANNEL_ID=$DISCORD_CHANNEL_ID" \
            --env "WANDERER_LICENSE_KEY=$LICENSE_KEY" \
            --env "WANDERER_ENV=test" \
            --env "WANDERER_FEATURE_DISABLE_WEBSOCKET=true" \
            --env "CHART_SERVICE_DIR=/tmp/chart-service"
          echo "Docker image validation successful!"
