name: Update Latest Docker Tag

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag to point latest to (e.g., v2.0.5)'
        required: true
        type: string

jobs:
  update-latest:
    name: Update Latest Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate version tag
        run: |
          # Check if the tag exists
          if ! git rev-parse "refs/tags/${{ github.event.inputs.version_tag }}" >/dev/null 2>&1; then
            echo "Error: Tag '${{ github.event.inputs.version_tag }}' does not exist"
            exit 1
          fi
          echo "Tag '${{ github.event.inputs.version_tag }}' exists, proceeding..."

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: guarzo
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Pull and retag image
        run: |
          # Pull the specific version
          docker pull guarzo/wanderer-notifier:${{ github.event.inputs.version_tag }}
          
          # Tag it as latest
          docker tag guarzo/wanderer-notifier:${{ github.event.inputs.version_tag }} guarzo/wanderer-notifier:latest
          
          # Push the latest tag
          docker push guarzo/wanderer-notifier:latest
      - name: Summary
        run: |
          echo "## ✅ Latest Tag Updated" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Updated:** \`guarzo/wanderer-notifier:latest\` → \`${{ github.event.inputs.version_tag }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Pull Command" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "docker pull guarzo/wanderer-notifier:latest" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
